services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: betmimi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./src/.env
    environment:
      - PYTHONPATH=/code/src
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: betmimi
    command: arq app.core.worker.settings.WorkerSettings
    env_file:
      - ./src/.env
    environment:
      - PYTHONPATH=/code/src
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    image: betmimi
    command: ["./wait-for-it.sh", "database-1.ch20kgo2scef.eu-north-1.rds.amazonaws.com:5432", "--", "sh", "-c", "alembic upgrade head"]
    env_file:
      - ./src/.env
    environment:
      - PYTHONPATH=/code/src
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
    volumes:
      - ./src/migrations:/code/migrations
      - ./src/alembic.ini:/code/alembic.ini

  create_superuser:
    build:
      context: .
      dockerfile: Dockerfile
    image: betmimi
    command: ["./wait-for-it.sh", "database-1.ch20kgo2scef.eu-north-1.rds.amazonaws.com:5432", "--", "python", "-m", "src.scripts.create_first_superuser"]
    env_file:
      - ./src/.env
    environment:
      - PYTHONPATH=/code/src
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - migrations
    volumes:
      - ./src:/code/src
      - ./src/.env:/code/.env
      - ./wait-for-it.sh:/wait-for-it.sh

volumes:
  redis-data: