"""Auto migration

Revision ID: 3d15fa4ea8f5
Revises: ca2121e534d8
Create Date: 2024-10-24 12:25:46.222835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d15fa4ea8f5'
down_revision: Union[str, None] = 'ca2121e534d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
