"""Auto migration

Revision ID: 3d92f8e3f197
Revises: bdaf76d2a798
Create Date: 2024-10-20 17:13:51.864321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d92f8e3f197'
down_revision: Union[str, None] = 'bdaf76d2a798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
