"""Auto migration

Revision ID: 4a6a94b05ae9
Revises: e44d4cbfe92a
Create Date: 2024-10-23 13:46:09.404289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6a94b05ae9'
down_revision: Union[str, None] = 'e44d4cbfe92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
