"""Auto migration

Revision ID: 7c92fe5f141d
Revises: 6bd1ea0b515d
Create Date: 2024-10-24 11:19:30.460802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c92fe5f141d'
down_revision: Union[str, None] = '6bd1ea0b515d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
