"""Auto migration

Revision ID: a0fdf4ba72bb
Revises: 0ffe98e97e04
Create Date: 2024-10-24 00:17:47.238363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0fdf4ba72bb'
down_revision: Union[str, None] = '0ffe98e97e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
